
development:
  cloud_name: 'dbenxy2yz'
  api_key: '649997533932585'
  api_secret: 'q_OghHSmVaXLZqFCt7J0iEAS09A'
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: 'dbenxy2yz'
  api_key: '649997533932585'
  api_secret: 'q_OghHSmVaXLZqFCt7J0iEAS09A'
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: 'dbenxy2yz'
  api_key: '649997533932585'
  api_secret: 'q_OghHSmVaXLZqFCt7J0iEAS09A'
  enhance_image_tag: true
  static_image_support: false
